### PR TITLE
Update for recent Zig 0.12, use .NET 6.0

### PR DESCRIPTION
**Pull request by vancluever**
This commit updates the repo to build with more recent versions of Zig 0.12, namely updating for semantic changes, e.g. enforcing const when values are not mutated, build API changes, generalization of readInt and writeInt, etc. This also updates the zig-args and parser-toolkit dependencies to accommodate.

Additionally, this updates svg2tvgt to build with .NET 6.0 versus 5.0, which is EOL and has been removed out of nixpkgs. This built without any other changes necessary.

### CODE REVIEW

**Comment by vancluever** [comment]
@MasterQ32 just FYI I don't think the changes to `build.zig` are backwards compatible as the build is failing here when I try it with Zig 0.11:

```
build.zig:94:34: error: type '?[]const u8' does not support struct initialization syntax
    generate_ground_truth.cwd = .{ .cwd_relative = b.cache_root.path.? };
                                ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Happy to hold off on this until there's a release if that's what you want to do and just maintain it on this end. I'm not too sure if there's a backwards compatible way to do these specific parts of the build step too.

Cheers!

**Comment by MasterQ32** [comment]
Can you split the PR into two parts?

One for stuff that works with 0.11, and one for 0.12-xxx stuff, you can target the `zig-master` branch for this PR then

**Comment by vancluever** [comment]
@MasterQ32 changed the base on this one to `zig-master`, will just put in a PR to update the .NET on the converter so that it builds without issue. I think pretty much everything here depends on Zig master now, even with the `build.zig` file reverted there are a ton of build issues surrounding `readInt`/`writeInt`, so I'm guessing that changed recently too.

**Comment by vancluever** [comment]
Updated - added the missed line back in the README mentioned in https://github.com/TinyVG/sdk/pull/19#discussion_r1435539924 and switched the Zig version in the workflow back to master (the default). Also rebased to address conflicts.
